services:
  stremio-addon-server:
    image: nyakaspeter/stremio-torrent-stream:latest
    container_name: stremio-addon-server
    ports:
      - 58827:58827
      - 58828:58828
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 9117:9117
    restart: unless-stopped